/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  collections: {
    users: User;
    media: Media;
    "portfolio-items": PortfolioItem;
    "virtual-tours": VirtualTour;
  };
  collectionsJoins: {};
  collectionsSelect: {};
  db: {
    defaultIDType: number;
  };
  globals: {
    "home-page": HomePage;
    "services-page": ServicesPage;
    "about-page": AboutPage;
    "contact-page": ContactPage;
  };
  globalsSelect: {};
  locale: null;
  user: User & { collection: "users" };
}

export interface UserAuthOperations {
  forgotPassword: { email: string; password: string };
  login: { email: string; password: string };
  registerFirstUser: { email: string; password: string };
  unlock: { email: string };
}

export interface User {
  id: number;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface Media {
  id: number;
  alt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
  createdAt: string;
  updatedAt: string;
}

export interface PortfolioItem {
  id: number;
  title?: string | null;
  image?: (number | null) | Media;
  category?: ("Aerial Photo" | "Video" | "3D Tours") | null;
  location?: string | null;
  description?: string | null;
  featured?: boolean | null;
  order?: number | null;
  createdAt: string;
  updatedAt: string;
}

export interface VirtualTour {
  id: number;
  title: string;
  description?: string | null;
  thumbnail?: (number | null) | Media;
  embedUrl?: string | null;
  externalLink?: string | null;
  location?: string | null;
  order?: number | null;
  createdAt: string;
  updatedAt: string;
}

export interface HomePage {
  id: number;
  heroHeadline?: string | null;
  heroAccent?: string | null;
  heroDescription?: string | null;
  heroImage?: (number | null) | Media;
  servicesHeading?: string | null;
  servicesDescription?: string | null;
  featuredHeading?: string | null;
  featuredDescription?: string | null;
  ctaHeading?: string | null;
  ctaDescription?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}

export interface ServicesPage {
  id: number;
  heading?: string | null;
  description?: string | null;
  services?:
    | {
        title?: string | null;
        subtitle?: string | null;
        description?: string | null;
        features?:
          | {
              feature?: string | null;
              id?: string | null;
            }[]
          | null;
        image?: (number | null) | Media;
        imageSize?: ("full" | "large" | "medium") | null;
        id?: string | null;
      }[]
    | null;
  ctaHeading?: string | null;
  ctaDescription?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}

export interface AboutPage {
  id: number;
  heading?: string | null;
  subtitle?: string | null;
  storyHeading?: string | null;
  storyImage?: (number | null) | Media;
  storyParagraphs?:
    | {
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  stats?:
    | {
        value?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  serviceAreaHeading?: string | null;
  serviceAreaDescription?: string | null;
  serviceAreas?:
    | {
        area?: string | null;
        id?: string | null;
      }[]
    | null;
  ctaHeading?: string | null;
  ctaDescription?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}

export interface ContactPage {
  id: number;
  heading?: string | null;
  description?: string | null;
  email?: string | null;
  serviceAreaDescription?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
